# Generated by Qodo Gen

from func import is_prime_number
import unittest

class TestIsPrimeNumber(unittest.TestCase):

    # Returns a string of prime numbers in a given range
    def test_returns_prime_numbers_in_range(self):
        result = is_prime_number(10, 20)
        self.assertEqual(result, "11 13 17 19 ")

    # Handles a range where a equals b
    def test_range_where_a_equals_b(self):
        result = is_prime_number(5, 5)
        self.assertEqual(result, "5 ")

    # Handles a range where a is greater than b
    def test_range_where_a_greater_than_b(self):
        result = is_prime_number(20, 10)
        self.assertEqual(result, "")